api:
  enabled: false
  url: https://api.warz.one
  auth: secret
  stats:
    enabled: true
rotation: Maps/rotation.txt
chat:
  enabled: true
  stats-hover: true
  messages:
    muted: "&cChat is currently disabled. If you believe this is an error, please contact a staff member on our Discord."
map:
  get-names: false
  save-matches: false
  sources:
  - Maps
server:
  name: "Warzone"
  id: "warzone"
  store: "https://tgmwarzone.tebex.io/"
  tablist-name: "&f&lWARZONE"
