api:
  enabled: false
  url: https://api.warz.one
  auth: secret
  stats:
    enabled: true
rotation: Maps/rotation.txt
chat:
  enabled: true
  messages:
    muted: "&cChat is currently disabled. If you believe this is an error, please contact a staff member on our Discord."
map:
  sources:
    - Maps
server:
  name: "Warzone"
  id: "warzone"
  ip: "play.warz.one"

links:
  store: https://tgmwarzone.tebex.io/
  website: https://warz.one/
  appeal: https://discord.io/WarzoneMC
  
