api:
  enabled: false
  url: api.team.gg
  auth: secret
  stats:
    enabled: true
rotation: maps/rotation.txt
chat:
  enabled: true
map:
  sources:
  - maps
server:
  name: "Warzone"
  id: "warzone"
